CREATE TABLE  IF NOT EXISTS public.project(
    project_id                              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                                                                                                                                     TEXT,
    project_deadline                                                                                                                DATE,
    description                                                                                                                            TEXT
)

CREATE TABLE IF NOT EXISTS public.milestone(
    
)