-- Скрипт по созданию физ. модели для проектного менеджера


-- Проект
CREATE TABLE  IF NOT EXISTS public.project(
    project_id                              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                                                                                                                                     TEXT,
    project_deadline                                                                                                                DATE,
    description                                                                                                                            TEXT
);
-- Проект

-- Статус
CREATE TABLE IF NOT EXISTS public.status(
    status_id                               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                                                                                                                                     TEXT
);
-- Статус

-- Тип
CREATE TABLE IF NOT EXISTS public.type(
    type_id                               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                                                                                                                                  TEXT
);
-- Тип

-- Промежуточные релизы
CREATE TABLE IF NOT EXISTS public.milestone(
    milestone_id                    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                                                                                                                                TEXT,
    description                                                                                                                       TEXT,
    status_id                                                                                                                    INTEGER,
    git_link                                                                                                                              TEXT,
    FOREIGN KEY (status_id) REFERENCES public.status (status_id) on DELETE CASCADE
);
-- Промежуточные релизы

-- Список релизов
CREATE TABLE IF NOT EXISTS public.milestone_list(
    list_id                                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id                                                                                                                  INTEGER,
    milestone_id                                                                                                             INTEGER,
    FOREIGN KEY (project_id) REFERENCES public.project (project_id) on DELETE CASCADE,
    FOREIGN KEY (milestone_id) REFERENCES public.milestone (milestone_id) on DELETE CASCADE
);
-- Список релизов

-- Задачи
CREATE TABLE IF NOT EXISTS public.task(
    task_id                                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                                                                                                                                   TEXT,
    description                                                                                                                          TEXT,
    type_id                                                                                                                          INTEGER,
    status_id                                                                                                                       INTEGER,
    task_deadline                                                                                                                    DATE,
    FOREIGN KEY (type_id) REFERENCES public.type (type_id) on DELETE CASCADE,
    FOREIGN KEY (status_id) REFERENCES public.status (status_id) on DELETE CASCADE
);
-- Задачи

-- Список задач
CREATE TABLE IF NOT EXISTS public.task_list(
    list_id                                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id                                                                                                                  INTEGER,
    milestone_id                                                                                                             INTEGER,
    task_id                                                                                                                        INTEGER,
    FOREIGN KEY (project_id) REFERENCES public.project (project_id) on DELETE CASCADE,
    FOREIGN KEY (milestone_id) REFERENCES public.milestone (milestone_id) on DELETE CASCADE,
    FOREIGN KEY (task_id) REFERENCES public.task (task_id) on DELETE CASCADE
);
-- Список задач